version: 2.1
jobs:
  unit-tests:
    docker:
      - image: bitnami/jsonnet:latest
        user: root
    steps:
      - checkout
      - run: "jsonnet unit-tests.jsonnet"
  integration-tests:
    docker:
      - image: bitnami/jsonnet:latest
        user: root
      - image: prom/prometheus:latest
    steps:
      - checkout
      - run: "apt-get update"
      - run: "apt-get -y install curl jq"
      - run: "./integration_tests.sh"
workflows:
  version: 2
  tests:
    jobs:
      - unit-tests
      - integration-tests
