version: 2.1
jobs:
  unit-tests:
    docker:
      - image: mexisme/jsonnet:latest
    steps:
      - checkout
      - run: "/jsonnet unit-tests.jsonnet"
  integration-tests:
    docker:
      - image: mexisme/jsonnet:latest
        user: root
      - image: prom/prometheus:latest
    steps:
      - checkout
      - run: "apk add --no-cache curl jq"
      - run: "export PATH=$PATH:/"
      - run: "./integration_tests.sh"
workflows:
  version: 2
  tests:
    jobs:
      - unit-tests
      - integration-tests
